### ISSUE TITLE
[JOSS Review] Tests

### ISSUE THREAD

**Issue by mbarzegary** [Sarc-Graph/sarcgraph#5]
Dear authors,

I see that the software has tests implemented using pytest procedures, and they are quite comprehensive in my opinion. However, since the software installation procedure installs the software from pip repositories (and not the cloned local repo), I think it can be nice if the test routines check proper installation too. At this moment, the tests can all pass without the `sarcgraph` package being installed in the virtual environment due to the presence of the `sarcgraph` directory. 

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5322

**Comment by saeedmhz** [comment]
Thank you for your feedback regarding the testing procedures for our software.

In response to your concerns, we have made changes to the installation process, as outlined in our previous response to Sarc-Graph/sarcgraph#3, which we believe address the issues you raised. Specifically, we have updated the installation instructions to allow users to install the developer version locally from the source code using the editable install command (``pip install -e .``). This ensures that the tests will be run on the source code, rather than on the package installed from the PyPI servers. Therefore, we believe that testing proper installation is not necessary anymore.

We are confident that the updated installation process, coupled with the comprehensive test procedures, will provide a robust testing framework for our software. We hope our revisions adequately address your concerns.

Please let us know if you have any further comments or suggestions.
